/* eslint-disable-line no-undef */ module.exports = {
	precision: 2,
	finalNewline: true,
	eol: "lf",
	multipass: true,
	plugins: [
		"removeDoctype",
		"removeXMLProcInst",
		"removeComments",
		"removeMetadata",
		"removeEditorsNSData",
		"cleanupAttrs",
		"mergeStyles",
		"inlineStyles",
		"minifyStyles",
		"cleanupIDs",
		"removeUselessDefs",
		"cleanupNumericValues",
		"convertColors",
		"removeUnknownsAndDefaults",
		"removeNonInheritableGroupAttrs",
		"removeUselessStrokeAndFill",
		"cleanupEnableBackground",
		"removeHiddenElems",
		"removeEmptyText",
		"convertShapeToPath",
		"convertEllipseToCircle",
		"moveElemsAttrsToGroup",
		"moveGroupAttrsToElems",
		"collapseGroups",
		"convertPathData",
		"convertTransform",
		"removeEmptyAttrs",
		"removeEmptyContainers",
		"mergePaths",
		"removeUnusedNS",
		"sortDefsChildren",
		"removeTitle",
		"removeDesc",
		"removeDimensions",
		"removeScriptElement",
	],
}
